# Generated by Django 2.0.5 on 2018-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=250, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=-1)),
                ('t_code', models.CharField(blank=True, max_length=200, null=True)),
                ('qty_in_reorder', models.IntegerField(default=0)),
            ],
        ),
    ]
